# SAAS PROJECT

In [1]:
# Import Libraries and Load Dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
DATA_PATH = Path(r"C:\Users\owner\Documents\Portfolio Projects\Ravenstack")

accounts = pd.read_csv(DATA_PATH / "ravenstack_accounts.csv")
subscriptions = pd.read_csv(DATA_PATH / "ravenstack_subscriptions.csv")
feature_usage = pd.read_csv(DATA_PATH / "ravenstack_feature_usage.csv")
support_tickets = pd.read_csv(DATA_PATH / "ravenstack_support_tickets.csv")
churn_events = pd.read_csv(DATA_PATH / "ravenstack_churn_events.csv")

In [3]:
# Store datasets in a dictionary
datasets = {
    "Accounts": accounts,
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

print("Datasets Loaded Successfully!")

Datasets Loaded Successfully!

In [4]:
# dataset Overview

overview = pd.DataFrame({
    "Dataset":[name for name in datasets.keys()],
    "Rows":[df.shape[0] for df in datasets.values()],
    "Columns":[df.shape[1] for df in datasets.values()]
})

overview

           Dataset   Rows  Columns
0         Accounts    500       10
1    Subscriptions   5000       14
2    Feature Usage  25000        8
3  Support Tickets   2000        9
4     Churn Events    600        9

In [5]:
# Display the First Five Rows

for name, df in datasets.items():
    print("="*80)
    print(name.upper())
    print("="*80)
    display(df.head())

================================================================================
ACCOUNTS
================================================================================

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

================================================================================
SUBSCRIPTIONS
================================================================================

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True

================================================================================
FEATURE USAGE
================================================================================

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

================================================================================
SUPPORT TICKETS
================================================================================

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

================================================================================
CHURN EVENTS
================================================================================

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [6]:
# Dataset Information
for name, df in datasets.items():
    print("="*80)
    print(name.upper())
    print("="*80)
    print(df.info())

================================================================================
ACCOUNTS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB
None
================================================================================
SUBSCRIPTIONS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB
None
================================================================================
FEATURE USAGE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB
None
================================================================================
SUPPORT TICKETS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   object
 1   account_id                   2000 non-null   object
 2   submitted_at                 2000 non-null   object
 3   closed_at                    2000 non-null   object
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB
None
================================================================================
CHURN EVENTS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB
None

In [7]:
# Check dataset shapes

datasets = {
    "Accounts": accounts,
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

Accounts: (500, 10)
Subscriptions: (5000, 14)
Feature Usage: (25000, 8)
Support Tickets: (2000, 9)
Churn Events: (600, 9)

In [8]:
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"], errors="coerce")

subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"], errors="coerce")
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"], errors="coerce")

feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"], errors="coerce")

support_tickets["submitted_at"] = pd.to_datetime(support_tickets["submitted_at"], errors="coerce")
support_tickets["closed_at"] = pd.to_datetime(support_tickets["closed_at"], errors="coerce")

churn_events["churn_date"] = pd.to_datetime(churn_events["churn_date"], errors="coerce")

In [9]:
analysis_date = max(
    accounts["signup_date"].max(),
    subscriptions["start_date"].max(),
    subscriptions["end_date"].max(),
    feature_usage["usage_date"].max(),
    support_tickets["submitted_at"].max(),
    support_tickets["closed_at"].max(),
    churn_events["churn_date"].max()
)

analysis_date

Timestamp('2024-12-31 19:00:00')

In [10]:
subscriptions["subscription_status"] = np.where(
    subscriptions["end_date"].isna(),
    "Active",
    "Ended"
)

subscriptions["effective_end_date"] = subscriptions["end_date"].fillna(analysis_date)

subscriptions["subscription_duration_days"] = (
    subscriptions["effective_end_date"] - subscriptions["start_date"]
).dt.days

subscriptions = subscriptions.drop(columns=["end_date"], errors="ignore")

In [11]:
support_tickets["satisfaction_missing"] = support_tickets["satisfaction_score"].isna().astype(int)

support_tickets["satisfaction_category"] = support_tickets["satisfaction_score"].astype("object")
support_tickets["satisfaction_category"] = support_tickets["satisfaction_category"].fillna("Not Rated")

support_tickets["satisfaction_score_imputed"] = (
    support_tickets
    .groupby("priority")["satisfaction_score"]
    .transform(lambda x: x.fillna(x.median()))
)

support_tickets["satisfaction_score_imputed"] = support_tickets["satisfaction_score_imputed"].fillna(
    support_tickets["satisfaction_score"].median()
)

support_tickets = support_tickets.drop(columns=["satisfaction_score"], errors="ignore")

In [12]:
churn_events["feedback_missing"] = churn_events["feedback_text"].isna().astype(int)
churn_events["feedback_text"] = churn_events["feedback_text"].fillna("No feedback provided")

In [13]:
accounts = accounts.drop_duplicates()
subscriptions = subscriptions.drop_duplicates()
feature_usage = feature_usage.drop_duplicates()
support_tickets = support_tickets.drop_duplicates()
churn_events = churn_events.drop_duplicates()

datasets = {
    "Accounts": accounts,
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

In [14]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)
    
    missing = pd.DataFrame({
        "Missing Values": df.isnull().sum(),
        "Percentage": round(df.isnull().mean() * 100, 2)
    })
    
    missing = missing[missing["Missing Values"] > 0]
    
    if len(missing) == 0:
        print("No Missing Values\n")
    else:
        display(missing.sort_values("Missing Values", ascending=False))

================================================================================
ACCOUNTS
================================================================================
No Missing Values

================================================================================
SUBSCRIPTIONS
================================================================================
No Missing Values

================================================================================
FEATURE USAGE
================================================================================
No Missing Values

================================================================================
SUPPORT TICKETS
================================================================================
No Missing Values

================================================================================
CHURN EVENTS
================================================================================
No Missing Values

In [15]:
# Unique Values
for name, df in datasets.items():

    print("="*80)
    print(name.upper())
    print("="*80)

    unique = pd.DataFrame({
        "Column":df.columns,
        "Unique Values":[df[col].nunique() for col in df.columns]
    })

    display(unique)

================================================================================
ACCOUNTS
================================================================================

            Column  Unique Values
0       account_id            500
1     account_name            500
2         industry              5
3          country              7
4      signup_date            370
5  referral_source              5
6        plan_tier              3
7            seats             73
8         is_trial              2
9       churn_flag              2

================================================================================
SUBSCRIPTIONS
================================================================================

                        Column  Unique Values
0              subscription_id           5000
1                   account_id            500
2                   start_date            625
3                    plan_tier              3
4                        seats            123
5                   mrr_amount            306
6                   arr_amount            306
7                     is_trial              2
8                 upgrade_flag              2
9               downgrade_flag              2
10                  churn_flag              2
11           billing_frequency              2
12             auto_renew_flag              2
13         subscription_status              2
14          effective_end_date            209
15  subscription_duration_days            612

================================================================================
FEATURE USAGE
================================================================================

                Column  Unique Values
0             usage_id          24979
1      subscription_id           4967
2           usage_date            731
3         feature_name             40
4          usage_count             27
5  usage_duration_secs           4168
6          error_count              9
7      is_beta_feature              2

================================================================================
SUPPORT TICKETS
================================================================================

                         Column  Unique Values
0                     ticket_id           2000
1                    account_id            492
2                  submitted_at            671
3                     closed_at           1893
4         resolution_time_hours             72
5                      priority              4
6   first_response_time_minutes            180
7               escalation_flag              2
8          satisfaction_missing              2
9         satisfaction_category              4
10   satisfaction_score_imputed              3

================================================================================
CHURN EVENTS
================================================================================

                     Column  Unique Values
0            churn_event_id            600
1                account_id            352
2                churn_date            311
3               reason_code              6
4         refund_amount_usd            142
5    preceding_upgrade_flag              2
6  preceding_downgrade_flag              2
7           is_reactivation              2
8             feedback_text              4
9          feedback_missing              2

In [16]:
# Data Quality Report

quality = []

for name, df in datasets.items():

    quality.append({
        "Dataset":name,
        "Rows":df.shape[0],
        "Columns":df.shape[1],
        "Missing Values":df.isnull().sum().sum(),
        "Duplicate Rows":df.duplicated().sum()
    })

quality = pd.DataFrame(quality)

quality

           Dataset   Rows  Columns  Missing Values  Duplicate Rows
0         Accounts    500       10               0               0
1    Subscriptions   5000       16               0               0
2    Feature Usage  25000        8               0               0
3  Support Tickets   2000       11               0               0
4     Churn Events    600       10               0               0

Exploratory Data Analysis

In [17]:
# Phase 3 Context:
# This phase creates the analysis tables needed for churn analysis, activation analysis,
# cohort retention, monthly revenue, and NRR reporting.

accounts["signup_month"] = accounts["signup_date"].dt.to_period("M").dt.to_timestamp()
subscriptions["start_month"] = subscriptions["start_date"].dt.to_period("M").dt.to_timestamp()
subscriptions["end_month"] = subscriptions["effective_end_date"].dt.to_period("M").dt.to_timestamp()
feature_usage["usage_month"] = feature_usage["usage_date"].dt.to_period("M").dt.to_timestamp()
support_tickets["submitted_month"] = support_tickets["submitted_at"].dt.to_period("M").dt.to_timestamp()
churn_events["churn_month"] = churn_events["churn_date"].dt.to_period("M").dt.to_timestamp()

In [18]:
# Churn by plan tier

plan_churn = (
    accounts
    .groupby("plan_tier")
    .agg(
        total_accounts=("account_id", "nunique"),
        churned_accounts=("churn_flag", "sum")
    )
    .reset_index()
)

plan_churn["churn_rate"] = plan_churn["churned_accounts"] / plan_churn["total_accounts"]

plan_churn.sort_values("churn_rate", ascending=False)

    plan_tier  total_accounts  churned_accounts  churn_rate
1  Enterprise             154                34    0.220779
0       Basic             168                37    0.220238
2         Pro             178                39    0.219101

In [19]:
# Churn by industry

industry_churn = (
    accounts
    .groupby("industry")
    .agg(
        total_accounts=("account_id", "nunique"),
        churned_accounts=("churn_flag", "sum")
    )
    .reset_index()
)

industry_churn["churn_rate"] = industry_churn["churned_accounts"] / industry_churn["total_accounts"]

industry_churn.sort_values("churn_rate", ascending=False)

        industry  total_accounts  churned_accounts  churn_rate
1       DevTools             113                35    0.309735
3        FinTech             112                25    0.223214
4     HealthTech              96                21    0.218750
2         EdTech              79                13    0.164557
0  Cybersecurity             100                16    0.160000

In [20]:
# Churn by country

country_churn = (
    accounts
    .groupby("country")
    .agg(
        total_accounts=("account_id", "nunique"),
        churned_accounts=("churn_flag", "sum")
    )
    .reset_index()
)

country_churn["churn_rate"] = country_churn["churned_accounts"] / country_churn["total_accounts"]

country_churn.sort_values("churn_rate", ascending=False)

  country  total_accounts  churned_accounts  churn_rate
2      DE              25                 8    0.320000
6      US             291                68    0.233677
3      FR              22                 5    0.227273
4      IN              49                10    0.204082
5      UK              58                11    0.189655
1      CA              23                 4    0.173913
0      AU              32                 4    0.125000

In [21]:
# Churn reasons

churn_reasons = (
    churn_events
    .groupby("reason_code")
    .agg(
        churn_events=("churn_event_id", "count"),
        affected_accounts=("account_id", "nunique"),
        avg_refund_amount=("refund_amount_usd", "mean"),
        total_refund_amount=("refund_amount_usd", "sum"),
        feedback_missing_rate=("feedback_missing", "mean")
    )
    .reset_index()
    .sort_values("churn_events", ascending=False)
)

churn_reasons

,reason_code,churn_events,affected_accounts,avg_refund_amount,total_refund_amount,feedback_missing_rate
2,features,114,104,16.718421,1905.90,0.280702
0,budget,104,94,11.995577,1247.54,0.269231
4,support,104,95,11.727308,1219.64,0.230769
5,unknown,95,86,18.340947,1742.39,0.231579
1,competitor,92,79,13.081848,1203.53,0.217391
3,pricing,91,86,14.651099,1333.25,0.241758

In [22]:
# Support experience by account

support_account_summary = (
    support_tickets
    .groupby("account_id")
    .agg(
        ticket_count=("ticket_id", "count"),
        avg_resolution_time_hours=("resolution_time_hours", "mean"),
        avg_first_response_time_minutes=("first_response_time_minutes", "mean"),
        escalation_count=("escalation_flag", "sum"),
        avg_satisfaction_score=("satisfaction_score_imputed", "mean"),
        unrated_ticket_count=("satisfaction_missing", "sum")
    )
    .reset_index()
)

support_churn_analysis = (
    accounts[["account_id", "churn_flag", "plan_tier", "industry", "country"]]
    .merge(support_account_summary, on="account_id", how="left")
)

support_columns = [
    "ticket_count",
    "avg_resolution_time_hours",
    "avg_first_response_time_minutes",
    "escalation_count",
    "avg_satisfaction_score",
    "unrated_ticket_count"
]

support_churn_analysis[support_columns] = support_churn_analysis[support_columns].fillna(0)

support_churn_analysis.head()

,account_id,churn_flag,plan_tier,industry,country,ticket_count,avg_resolution_time_hours,avg_first_response_time_minutes,escalation_count,avg_satisfaction_score,unrated_ticket_count
0,A-2e4581,False,Basic,EdTech,US,2.0,23.000000,91.000000,0.0,3.500000,1.0
1,A-43a9e3,True,Basic,FinTech,IN,3.0,38.000000,73.333333,0.0,4.000000,0.0
2,A-0a282f,False,Basic,DevTools,US,3.0,43.666667,63.666667,0.0,4.666667,0.0
3,A-1f0ac7,False,Basic,HealthTech,UK,2.0,29.000000,174.000000,0.0,4.000000,2.0
4,A-ce550d,True,Enterprise,HealthTech,US,7.0,42.285714,107.857143,1.0,3.857143,2.0

In [23]:
# Compare support experience for churned vs retained customers

support_churn_summary = (
    support_churn_analysis
    .groupby("churn_flag")
    .agg(
        accounts=("account_id", "nunique"),
        avg_ticket_count=("ticket_count", "mean"),
        avg_resolution_time_hours=("avg_resolution_time_hours", "mean"),
        avg_first_response_time_minutes=("avg_first_response_time_minutes", "mean"),
        avg_escalation_count=("escalation_count", "mean"),
        avg_satisfaction_score=("avg_satisfaction_score", "mean"),
        avg_unrated_ticket_count=("unrated_ticket_count", "mean")
    )
    .reset_index()
)

support_churn_summary

,churn_flag,accounts,avg_ticket_count,avg_resolution_time_hours,avg_first_response_time_minutes,avg_escalation_count,avg_satisfaction_score,avg_unrated_ticket_count
0,False,390,4.020513,35.889532,88.203733,0.182051,3.910561,1.674359
1,True,110,3.927273,34.840292,83.382821,0.218182,3.913167,1.563636

In [24]:
# First 7 days product activation
# This identifies product usage during the first 7 days after subscription start.

activation_base = (
    feature_usage
    .merge(
        subscriptions[["subscription_id", "account_id", "start_date"]],
        on="subscription_id",
        how="left"
    )
)

activation_base["days_since_subscription_start"] = (
    activation_base["usage_date"] - activation_base["start_date"]
).dt.days

activation_7d = activation_base[
    (activation_base["days_since_subscription_start"] >= 0) &
    (activation_base["days_since_subscription_start"] <= 7)
].copy()

activation_7d.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature,usage_month,account_id,start_date,days_since_subscription_start
87,U-e5b4b3,S-c2f293,2024-12-12,feature_39,10,1340,0,False,2024-12-01,A-69b156,2024-12-10,2
101,U-bc70f2,S-34b845,2024-05-05,feature_35,10,2260,2,False,2024-05-01,A-432483,2024-05-02,3
352,U-cd7803,S-573f93,2024-10-31,feature_6,8,4024,3,False,2024-10-01,A-50bb9f,2024-10-29,2
479,U-39b9a6,S-d111f5,2024-06-01,feature_22,8,968,0,True,2024-06-01,A-f03140,2024-05-25,7
513,U-227149,S-bb84b1,2023-10-19,feature_26,8,2296,0,False,2023-10-01,A-af0cd2,2023-10-12,7

In [25]:
# Activation summary by account

activation_account_summary = (
    activation_7d
    .groupby("account_id")
    .agg(
        activation_events_7d=("usage_id", "count"),
        activation_features_used_7d=("feature_name", "nunique"),
        activation_total_usage_7d=("usage_count", "sum"),
        activation_total_duration_secs_7d=("usage_duration_secs", "sum"),
        activation_total_errors_7d=("error_count", "sum"),
        beta_feature_used_7d=("is_beta_feature", "max")
    )
    .reset_index()
)

activation_churn_analysis = (
    accounts[["account_id", "churn_flag", "plan_tier", "industry", "country"]]
    .merge(activation_account_summary, on="account_id", how="left")
)

activation_columns = [
    "activation_events_7d",
    "activation_features_used_7d",
    "activation_total_usage_7d",
    "activation_total_duration_secs_7d",
    "activation_total_errors_7d",
    "beta_feature_used_7d"
]

activation_churn_analysis[activation_columns] = activation_churn_analysis[activation_columns].fillna(0)

activation_churn_analysis.head()

,account_id,churn_flag,plan_tier,industry,country,activation_events_7d,activation_features_used_7d,activation_total_usage_7d,activation_total_duration_secs_7d,activation_total_errors_7d,beta_feature_used_7d
0,A-2e4581,False,Basic,EdTech,US,0.0,0.0,0.0,0.0,0.0,0
1,A-43a9e3,True,Basic,FinTech,IN,0.0,0.0,0.0,0.0,0.0,0
2,A-0a282f,False,Basic,DevTools,US,1.0,1.0,7.0,749.0,2.0,False
3,A-1f0ac7,False,Basic,HealthTech,UK,0.0,0.0,0.0,0.0,0.0,0
4,A-ce550d,True,Enterprise,HealthTech,US,1.0,1.0,9.0,3519.0,0.0,False

In [26]:
# Compare activation behavior for churned vs retained customers

activation_churn_summary = (
    activation_churn_analysis
    .groupby("churn_flag")
    .agg(
        accounts=("account_id", "nunique"),
        avg_activation_events_7d=("activation_events_7d", "mean"),
        avg_features_used_7d=("activation_features_used_7d", "mean"),
        avg_total_usage_7d=("activation_total_usage_7d", "mean"),
        avg_duration_secs_7d=("activation_total_duration_secs_7d", "mean"),
        avg_errors_7d=("activation_total_errors_7d", "mean"),
        beta_feature_usage_rate_7d=("beta_feature_used_7d", "mean")
    )
    .reset_index()
)

activation_churn_summary

,churn_flag,accounts,avg_activation_events_7d,avg_features_used_7d,avg_total_usage_7d,avg_duration_secs_7d,avg_errors_7d,beta_feature_usage_rate_7d
0,False,390,0.517949,0.515385,5.087179,1609.346154,0.266667,0.046154
1,True,110,0.600000,0.600000,6.300000,2021.063636,0.190909,0.063636

In [27]:
# Compare activation behavior for churned vs retained customers

activation_churn_summary = (
    activation_churn_analysis
    .groupby("churn_flag")
    .agg(
        accounts=("account_id", "nunique"),
        avg_activation_events_7d=("activation_events_7d", "mean"),
        avg_features_used_7d=("activation_features_used_7d", "mean"),
        avg_total_usage_7d=("activation_total_usage_7d", "mean"),
        avg_duration_secs_7d=("activation_total_duration_secs_7d", "mean"),
        avg_errors_7d=("activation_total_errors_7d", "mean"),
        beta_feature_usage_rate_7d=("beta_feature_used_7d", "mean")
    )
    .reset_index()
)

activation_churn_summary

,churn_flag,accounts,avg_activation_events_7d,avg_features_used_7d,avg_total_usage_7d,avg_duration_secs_7d,avg_errors_7d,beta_feature_usage_rate_7d
0,False,390,0.517949,0.515385,5.087179,1609.346154,0.266667,0.046154
1,True,110,0.600000,0.600000,6.300000,2021.063636,0.190909,0.063636

In [28]:
# Feature-level activation and churn analysis

feature_activation_retention = (
    activation_7d
    .merge(accounts[["account_id", "churn_flag"]], on="account_id", how="left")
    .groupby("feature_name")
    .agg(
        accounts_using_feature_7d=("account_id", "nunique"),
        churned_accounts=("churn_flag", "sum"),
        avg_usage_count=("usage_count", "mean"),
        avg_duration_secs=("usage_duration_secs", "mean"),
        avg_error_count=("error_count", "mean")
    )
    .reset_index()
)

feature_activation_retention["churn_rate"] = (
    feature_activation_retention["churned_accounts"] /
    feature_activation_retention["accounts_using_feature_7d"]
)

feature_activation_retention.sort_values("churn_rate")

,feature_name,accounts_using_feature_7d,churned_accounts,avg_usage_count,avg_duration_secs,avg_error_count,churn_rate
36,feature_6,6,0,9.333333,4272.000000,0.833333,0.000000
35,feature_5,4,0,8.500000,1776.000000,0.250000,0.000000
4,feature_13,7,0,9.428571,3350.571429,0.571429,0.000000
38,feature_8,4,0,10.500000,3114.250000,0.500000,0.000000
27,feature_34,9,0,8.444444,2877.888889,0.555556,0.000000
26,feature_33,7,0,10.000000,3563.857143,0.857143,0.000000
14,feature_22,12,0,8.916667,2729.416667,0.666667,0.000000
17,feature_25,9,1,9.000000,2718.888889,0.333333,0.111111
33,feature_4,9,1,10.222222,3599.222222,1.333333,0.111111
5,feature_14,8,1,6.625000,2457.375000,0.375000,0.125000
24,feature_31,8,1,8.625000,2051.750000,0.250000,0.125000
12,feature_20,11,2,11.818182,4467.181818,0.090909,0.181818
6,feature_15,5,1,12.600000,3403.400000,0.600000,0.200000
15,feature_23,5,1,11.600000,5451.200000,0.200000,0.200000
3,feature_12,14,3,9.428571,2673.571429,0.571429,0.214286
28,feature_35,9,2,9.555556,2417.222222,1.000000,0.222222
0,feature_1,4,1,7.000000,1339.250000,1.250000,0.250000
29,feature_36,4,1,10.500000,3415.250000,0.000000,0.250000
39,feature_9,8,2,9.625000,2555.250000,0.000000,0.250000
13,feature_21,4,1,11.750000,3016.000000,0.500000,0.250000
23,feature_30,7,2,10.428571,1803.571429,0.714286,0.285714
11,feature_2,7,2,11.714286,3684.000000,0.285714,0.285714
18,feature_26,10,3,11.000000,2584.300000,0.900000,0.300000
2,feature_11,6,2,10.000000,4119.833333,0.000000,0.333333
25,feature_32,3,1,11.000000,2941.000000,0.000000,0.333333
7,feature_16,9,3,10.333333,3689.555556,0.111111,0.333333
31,feature_38,11,4,12.272727,3752.818182,0.181818,0.363636
37,feature_7,8,3,10.000000,3075.250000,0.250000,0.375000
16,feature_24,5,2,8.000000,3085.600000,0.000000,0.400000
1,feature_10,5,2,10.800000,1602.000000,0.000000,0.400000
34,feature_40,5,2,11.800000,3350.800000,0.800000,0.400000
32,feature_39,5,2,9.833333,2454.833333,0.666667,0.400000
19,feature_27,5,2,9.000000,2790.000000,0.000000,0.400000
30,feature_37,7,3,8.857143,2862.428571,0.000000,0.428571
9,feature_18,6,3,11.333333,3699.666667,0.333333,0.500000
10,feature_19,8,4,10.000000,4562.500000,0.750000,0.500000
22,feature_3,4,2,9.500000,4136.250000,0.750000,0.500000
8,feature_17,4,2,11.250000,3878.750000,0.750000,0.500000
21,feature_29,3,2,10.333333,4367.666667,0.666667,0.666667
20,feature_28,2,2,10.500000,5500.500000,0.000000,1.000000

In [29]:
# Cohort retention analysis
# Cohort month is based on the subscription start month.

cohort_base = subscriptions.copy()
cohort_base["cohort_month"] = cohort_base["start_month"]

month_range = pd.date_range(
    cohort_base["start_month"].min(),
    analysis_date,
    freq="MS"
)

cohort_rows = []

for _, row in cohort_base.iterrows():
    active_months = month_range[
        (month_range >= row["start_month"]) &
        (month_range <= row["end_month"])
    ]

    for active_month in active_months:
        cohort_rows.append({
            "subscription_id": row["subscription_id"],
            "account_id": row["account_id"],
            "cohort_month": row["cohort_month"],
            "active_month": active_month,
            "mrr_amount": row["mrr_amount"],
            "arr_amount": row["arr_amount"],
            "plan_tier": row["plan_tier"],
            "subscription_status": row["subscription_status"]
        })

cohort_activity = pd.DataFrame(cohort_rows)

cohort_activity["cohort_index"] = (
    (cohort_activity["active_month"].dt.year - cohort_activity["cohort_month"].dt.year) * 12 +
    (cohort_activity["active_month"].dt.month - cohort_activity["cohort_month"].dt.month)
)

cohort_activity.head()

,subscription_id,account_id,cohort_month,active_month,mrr_amount,arr_amount,plan_tier,subscription_status,cohort_index
0,S-8cec59,A-3c1a3f,2023-12-01,2023-12-01,2786,33432,Enterprise,Ended,0
1,S-8cec59,A-3c1a3f,2023-12-01,2024-01-01,2786,33432,Enterprise,Ended,1
2,S-8cec59,A-3c1a3f,2023-12-01,2024-02-01,2786,33432,Enterprise,Ended,2
3,S-8cec59,A-3c1a3f,2023-12-01,2024-03-01,2786,33432,Enterprise,Ended,3
4,S-8cec59,A-3c1a3f,2023-12-01,2024-04-01,2786,33432,Enterprise,Ended,4

In [30]:
# Cohort retention matrix

cohort_counts = (
    cohort_activity
    .groupby(["cohort_month", "cohort_index"])
    .agg(active_accounts=("account_id", "nunique"))
    .reset_index()
)

cohort_sizes = (
    cohort_counts[cohort_counts["cohort_index"] == 0]
    [["cohort_month", "active_accounts"]]
    .rename(columns={"active_accounts": "cohort_size"})
)

cohort_retention = cohort_counts.merge(cohort_sizes, on="cohort_month", how="left")

cohort_retention["retention_rate"] = (
    cohort_retention["active_accounts"] / cohort_retention["cohort_size"]
)

cohort_retention_matrix = cohort_retention.pivot_table(
    index="cohort_month",
    columns="cohort_index",
    values="retention_rate"
)

cohort_retention_matrix

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
cohort_month,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
2023-02-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.888889,0.888889,0.888889,0.777778,0.777778,0.777778,0.777778,0.777778,0.777778,0.777778,0.666667,0.666667,0.666667,0.666667,0.666667,0.666667,NaN
2023-03-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN
2023-04-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,0.960000,NaN,NaN,NaN
2023-05-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.961538,0.923077,0.923077,0.923077,0.923077,0.923077,0.923077,0.846154,0.846154,0.846154,0.846154,0.846154,NaN,NaN,NaN,NaN
2023-06-01,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.972222,0.972222,0.972222,0.972222,0.972222,NaN,NaN,NaN,NaN,NaN
2023-07-01,1.0,1.000000,1.000000,1.000000,0.977778,0.933333,0.933333,0.933333,0.933333,0.933333,0.911111,0.911111,0.911111,0.888889,0.888889,0.888889,0.866667,0.844444,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-01,1.0,1.000000,1.000000,1.000000,0.984127,0.984127,0.984127,0.984127,0.984127,0.984127,0.968254,0.952381,0.952381,0.952381,0.952381,0.936508,0.936508,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09-01,1.0,1.000000,0.980392,0.941176,0.941176,0.901961,0.882353,0.862745,0.862745,0.843137,0.843137,0.823529,0.823529,0.823529,0.823529,0.803922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10-01,1.0,1.000000,1.000000,0.984615,0.969231,0.953846,0.938462,0.938462,0.938462,0.938462,0.938462,0.923077,0.923077,0.907692,0.907692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11-01,1.0,1.000000,0.988372,0.976744,0.953488,0.953488,0.953488,0.953488,0.941860,0.941860,0.941860,0.941860,0.906977,0.895349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-01,1.0,1.000000,0.989247,0.989247,0.978495,0.978495,0.978495,0.978495,0.967742,0.967742,0.956989,0.946237,0.935484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-01,1.0,0.980583,0.970874,0.961165,0.932039,0.922330,0.912621,0.912621,0.912621,0.912621,0.902913,0.893204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-02-01,1.0,1.000000,0.981982,0.972973,0.963964,0.954955,0.954955,0.945946,0.945946,0.927928,0.918919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03-01,1.0,1.000000,1.000000,0.986301,0.986301,0.986301,0.986301,0.979452,0.972603,0.972603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-04-01,1.0,1.000000,0.992701,0.992701,0.978102,0.978102,0.970803,0.970803,0.963504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-01,1.0,1.000000,1.000000,0.988095,0.982143,0.970238,0.952381,0.946429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06-01,1.0,0.994048,0.994048,0.982143,0.976190,0.970238,0.958333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07-01,1.0,1.000000,0.986175,0.986175,0.976959,0.967742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-08-01,1.0,1.000000,0.990566,0.971698,0.957547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-01,1.0,0.995968,0.987903,0.975806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-01,1.0,0.996337,0.974359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11-01,1.0,0.983333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Monthly revenue trend

monthly_revenue = (
    cohort_activity
    .groupby("active_month")
    .agg(
        active_accounts=("account_id", "nunique"),
        active_subscriptions=("subscription_id", "nunique"),
        total_mrr=("mrr_amount", "sum"),
        total_arr=("arr_amount", "sum")
    )
    .reset_index()
    .sort_values("active_month")
)

monthly_revenue["mrr_growth_rate"] = monthly_revenue["total_mrr"].pct_change()
monthly_revenue["arr_growth_rate"] = monthly_revenue["total_arr"].pct_change()

monthly_revenue.head()

,active_month,active_accounts,active_subscriptions,total_mrr,total_arr,mrr_growth_rate,arr_growth_rate
0,2023-01-01,2,3,4684,56208,NaN,NaN
1,2023-02-01,10,14,15763,189156,2.365286,2.365286
2,2023-03-01,21,31,41648,499776,1.642137,1.642137
3,2023-04-01,36,62,83436,1001232,1.003362,1.003362
4,2023-05-01,50,90,169110,2029320,1.026823,1.026823

In [32]:
# Monthly churn analysis

monthly_churn = (
    churn_events
    .groupby("churn_month")
    .agg(
        churn_events=("churn_event_id", "count"),
        churned_accounts=("account_id", "nunique"),
        total_refunds=("refund_amount_usd", "sum")
    )
    .reset_index()
    .rename(columns={"churn_month": "month"})
)

monthly_active = (
    monthly_revenue
    .rename(columns={"active_month": "month"})
    [["month", "active_accounts", "total_mrr", "total_arr"]]
)

monthly_churn_analysis = monthly_active.merge(monthly_churn, on="month", how="left")

monthly_churn_analysis[["churn_events", "churned_accounts", "total_refunds"]] = (
    monthly_churn_analysis[["churn_events", "churned_accounts", "total_refunds"]].fillna(0)
)

monthly_churn_analysis["account_churn_rate"] = (
    monthly_churn_analysis["churned_accounts"] / monthly_churn_analysis["active_accounts"]
)

monthly_churn_analysis.head()

,month,active_accounts,total_mrr,total_arr,churn_events,churned_accounts,total_refunds,account_churn_rate
0,2023-01-01,2,4684,56208,1.0,1.0,0.00,0.500000
1,2023-02-01,10,15763,189156,0.0,0.0,0.00,0.000000
2,2023-03-01,21,41648,499776,5.0,5.0,0.00,0.238095
3,2023-04-01,36,83436,1001232,3.0,3.0,38.15,0.083333
4,2023-05-01,50,169110,2029320,3.0,3.0,0.00,0.060000

In [33]:
# NRR analysis
# This is a simplified NRR table using monthly active MRR and churned MRR.

new_revenue = (
    subscriptions
    .groupby("start_month")
    .agg(
        new_mrr=("mrr_amount", "sum"),
        new_arr=("arr_amount", "sum")
    )
    .reset_index()
    .rename(columns={"start_month": "month"})
)

churned_revenue = (
    subscriptions[subscriptions["subscription_status"] == "Ended"]
    .groupby("end_month")
    .agg(
        churned_mrr=("mrr_amount", "sum"),
        churned_arr=("arr_amount", "sum")
    )
    .reset_index()
    .rename(columns={"end_month": "month"})
)

nrr_table = (
    monthly_active
    .merge(new_revenue, on="month", how="left")
    .merge(churned_revenue, on="month", how="left")
)

nrr_table[["new_mrr", "new_arr", "churned_mrr", "churned_arr"]] = (
    nrr_table[["new_mrr", "new_arr", "churned_mrr", "churned_arr"]].fillna(0)
)

nrr_table["starting_mrr"] = nrr_table["total_mrr"].shift(1)

nrr_table["gross_revenue_churn_rate"] = (
    nrr_table["churned_mrr"] / nrr_table["starting_mrr"]
)

nrr_table["nrr"] = (
    (nrr_table["starting_mrr"] - nrr_table["churned_mrr"]) /
    nrr_table["starting_mrr"]
)

nrr_table.head()

,month,active_accounts,total_mrr,total_arr,new_mrr,new_arr,churned_mrr,churned_arr,starting_mrr,gross_revenue_churn_rate,nrr
0,2023-01-01,2,4684,56208,4684,56208,0.0,0.0,NaN,NaN,NaN
1,2023-02-01,10,15763,189156,11079,132948,0.0,0.0,4684.0,0.000000,1.000000
2,2023-03-01,21,41648,499776,25885,310620,0.0,0.0,15763.0,0.000000,1.000000
3,2023-04-01,36,83436,1001232,41788,501456,245.0,2940.0,41648.0,0.005883,0.994117
4,2023-05-01,50,169110,2029320,85919,1031028,0.0,0.0,83436.0,0.000000,1.000000

In [34]:
# Export Phase 3 analysis tables for Power BI

OUTPUT_PATH = Path(r"C:\Users\owner\Documents\Portfolio Projects")

plan_churn.to_csv(OUTPUT_PATH / "plan_churn.csv", index=False)
industry_churn.to_csv(OUTPUT_PATH / "industry_churn.csv", index=False)
country_churn.to_csv(OUTPUT_PATH / "country_churn.csv", index=False)
churn_reasons.to_csv(OUTPUT_PATH / "churn_reasons.csv", index=False)

support_churn_analysis.to_csv(OUTPUT_PATH / "support_churn_analysis.csv", index=False)
support_churn_summary.to_csv(OUTPUT_PATH / "support_churn_summary.csv", index=False)

activation_churn_analysis.to_csv(OUTPUT_PATH / "activation_churn_analysis.csv", index=False)
activation_churn_summary.to_csv(OUTPUT_PATH / "activation_churn_summary.csv", index=False)
feature_activation_retention.to_csv(OUTPUT_PATH / "feature_activation_retention.csv", index=False)

cohort_activity.to_csv(OUTPUT_PATH / "cohort_activity.csv", index=False)
cohort_retention.to_csv(OUTPUT_PATH / "cohort_retention_long.csv", index=False)
cohort_retention_matrix.to_csv(OUTPUT_PATH / "cohort_retention_matrix.csv")

monthly_revenue.to_csv(OUTPUT_PATH / "monthly_revenue.csv", index=False)
monthly_churn_analysis.to_csv(OUTPUT_PATH / "monthly_churn_analysis.csv", index=False)
nrr_table.to_csv(OUTPUT_PATH / "nrr_table.csv", index=False)

print(f"Phase 3 analysis tables saved to: {OUTPUT_PATH}")

Phase 3 analysis tables saved to: C:\Users\owner\Documents\Portfolio Projects

In [35]:
# ==========================================
# EXPORT CLEANED DATASETS
# ==========================================

from pathlib import Path

OUTPUT_PATH = DATA_PATH / "cleaned_outputs"
OUTPUT_PATH.mkdir(exist_ok=True)

# Export cleaned raw datasets
accounts.to_csv(
    OUTPUT_PATH / "cleaned_accounts.csv",
    index=False
)

subscriptions.to_csv(
    OUTPUT_PATH / "cleaned_subscriptions.csv",
    index=False
)

feature_usage.to_csv(
    OUTPUT_PATH / "cleaned_feature_usage.csv",
    index=False
)

support_tickets.to_csv(
    OUTPUT_PATH / "cleaned_support_tickets.csv",
    index=False
)

churn_events.to_csv(
    OUTPUT_PATH / "cleaned_churn_events.csv",
    index=False
)

print("Cleaned datasets exported successfully!")
print(f"Location: {OUTPUT_PATH}")

Cleaned datasets exported successfully!
Location: C:\Users\owner\Documents\Portfolio Projects\Ravenstack\cleaned_outputs